services:
  - type: web
    name: certificate-generator
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ADMIN_PASSWORD
        value: RavalMegh9898@
